### PR TITLE
Experimental Linux support

### PR DESCRIPTION
**Pull request by gtrxAC**
Some minor fixes to make it compile on Linux. Don't know if it compiles on Windows. Also added build instructions to the readme.

`convert_path` doesn't work on Linux because of path separators, so many apps will just crash.

### CODE REVIEW

**Comment by XimikBoda** [comment]
Try these fixes

**Comment by gtrxAC** [comment]
The path still doesn't work, like before, it gives me something like this:
```
--vm_file_mkdir-- called
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character
Aborted (core dumped)
```
It crashes at IO.cpp line 19: `fs::path path = (wchar_t*)str, res = ".\\fs\\";`

**Comment by XimikBoda** [comment]
The problem is that wchar_t on Linux is 4 bytes, which makes it incompatible with mre application strings, which means Linux support will appear only after adding the string conversion library (I'm thinking about libiconv)

**Comment by XimikBoda** [comment]
libiconv was added to the main branch, and conversions between UTF-8 and UCS2 were made, and now there seem to be no problems on Linux

**Pull request closed without merging**
